export enum DepositStatus {
  PENDING = "PENDING",
  AUTHORIZED = "AUTHORIZED",
  CONFIRMED = "CONFIRMED",
  REFUNDED = "REFUNDED",
  CANCELLED = "CANCELLED",
  EXPIRED = "EXPIRED",
  FAILED = "FAILED",
}
